services:
  app:
    build: .
    container_name: project-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app        # 👈 подключаем код с хоста
      - /app/node_modules   # ✅ обязательный внутренний том

    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: project-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
